# external_url 'GENERATED_EXTERNAL_URL' # default: http://hostname
external_url "http://gitlab.xendebian.local:80/"
#
#...
#...
#...
#...
#
# ## GitLab Shell settings for GitLab
gitlab_rails['gitlab_shell_ssh_port'] = 2234
